config/routes.rb
Wenchang::Application.routes.draw do
  resources :papers do
    member do
      post :add_favor
    end
  end

  get "acm/fetch"
  post "acm/mail"
  get "acm/search"
  post "acm/search"

  get "users/show"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

   root :to => 'users#show'

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  attr_accessible :paper_id, :user_id
  belongs_to :user
  belongs_to :paper
end

app/models/paper.rb
class Paper < ActiveRecord::Base
  attr_accessible :abstract, :link, :title, :published_at, :source,:acm_id
  has_many :favorites
  has_many :users,:through=>:favorites
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:omniauthable
  has_many :favorites,:order=>"created_at DESC"
  has_many :favorite_paper,:through=>:favorites,:source=>:paper

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,:provider, :uid
  # attr_accessible :title, :body
  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    unless user
      user = User.create(
                         provider:auth.provider,
                         uid:auth.uid,
                         email:auth.info.email,
                         password:Devise.friendly_token[0,20]
                        )
    end
    user
  end
end

app/controllers/acm_controller.rb
class AcmController < ApplicationController
  def fetch
    @email =  ""
    @email = current_user.email  if user_signed_in?
  end

  def mail
    p params[:page]
   Delayed::Job.enqueue(DelayedRake.new("download",:page=>params[:page])) 
   render :text=>"ok"
  end

  def search
    if params[:keyword].nil?
      render
    else
      result = do_search(params[:keyword])
      render :json=>result
    end
    
  end


  private

  def do_search keyword
           baseUrl="http://dl.acm.org"
        conn = Faraday.new(:url => baseUrl) do |faraday|
            faraday.request  :url_encoded             # form-encode POST params
            faraday.response :logger                  # log requests to STDOUT
            faraday.adapter  Faraday.default_adapter  # make requests with Net::HTTP
        end 
        response =conn.post "/results.cfm",{:query=>keyword}
        doc =Nokogiri::HTML(response.body)
        #  doc =Nokogiri::HTML(open("test.html"))
        # find  published date
        table = doc.css("table")[10]
        i=0 
        articles=[]
        for a_table in table.xpath("//tr[3]/td/table/tr[3]/td[2]/table/tr/td[2]/table")
            title = a_table.search("tr")[0].search("td/a")[0].text.strip
            link = a_table.search("tr")[0].search("td/a")[0]["href"]
            match = link.match(/id=(\d+)/)
            acm_id=nil
            acm_id = match[1] unless match[1].nil?
            authors =[] 

            for author in a_table.search("tr")[0].search("td[1]/div/a")
                authors.push({
                    :name=>author.text,
                    :link=>baseUrl+"/"+author["href"]
                })  
            end 
            date = a_table.search("tr")[1].search("td")[0].text.strip
            publisher  = a_table.search("tr")[2].search("td")[0].text.strip
            abstract,keyword = a_table.search("div.abstract2").text.strip.split("...")
            abstract.strip! unless abstract.nil?
            keyword = (keyword.strip)[10...-1] unless keyword.nil?
            #加到資料庫裡面
            
            paper = Paper.find_by_acm_id(acm_id)
            id=nil
            if paper.nil?
              id=Paper.new(:title=>title,
                        :source=>"acm",
                        :abstract=>abstract,
                        :acm_id=>acm_id,
                        :published_at=>:date,
                        :link=>link
                       ).save
            else
              id=paper.id
            end

            articles.push({
                :id=>id,
                :title=>title,
                :link=>baseUrl+"/"+link,
                :authors=>authors, 
                :date=>date,
                :publisher => publisher[11..-1],
                :abstract=> abstract,
                :keyword => keyword,
                :acm_id=>acm_id
            })
        end
        return articles
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/papers_controller.rb
class PapersController < ApplicationController
  # GET /papers
  # GET /papers.json
  def index
    @papers = Paper.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @papers }
    end
  end

  # GET /papers/1
  # GET /papers/1.json
  def show
    @paper = Paper.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @paper }
    end
  end

  # GET /papers/new
  # GET /papers/new.json
  def new
    @paper = Paper.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @paper }
    end
  end

  # GET /papers/1/edit
  def edit
    @paper = Paper.find(params[:id])
  end

  # POST /papers
  # POST /papers.json
  def create
    @paper = Paper.new(params[:paper])

    respond_to do |format|
      if @paper.save
        format.html { redirect_to @paper, notice: 'Paper was successfully created.' }
        format.json { render json: @paper, status: :created, location: @paper }
      else
        format.html { render action: "new" }
        format.json { render json: @paper.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /papers/1
  # PUT /papers/1.json
  def update
    @paper = Paper.find(params[:id])

    respond_to do |format|
      if @paper.update_attributes(params[:paper])
        format.html { redirect_to @paper, notice: 'Paper was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @paper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /papers/1
  # DELETE /papers/1.json
  def destroy
    @paper = Paper.find(params[:id])
    @paper.destroy

    respond_to do |format|
      format.html { redirect_to papers_url }
      format.json { head :no_content }
    end
  end

  def add_favor
    @favor = Favorite.where(:paper_id=>params[:id],:user_id=>current_user.id)
    unless @favor.presence
      current_user.favorite_paper<<Paper.find(params[:id])
    end
    redirect_to :back,:notice=>"add ok"
    
  end


end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook # You need to implement the method below in your model @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user) 
     @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)
    if @user.persisted?
#        logger.debug "user.persised"
        flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook"
        sign_in_and_redirect @user, :event => :authentication
    else
      logger.debug "user.nopersised"
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  def show
    @user = current_user || User.find(:id)
  end
end

app/helpers/acm_helper.rb
module AcmHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/papers_helper.rb
module PapersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/acm/fetch.html.erb
<form action="/acm/mail" method="post" class="form">
            <div class="input-prepend">
                <span class="add-on"><i class="icon-home"></i></span>
                <input class="span2" id="page" name="page" value="<%=@ref%>" type="text" placeholder="Acm Webpage" style="width:400px;"> (acm only)
            </div>
            <div class="input-prepend">
                <span class="add-on"><i class='icon-envelope' ></i></span>
                <input class="span2" id="email" name="email" value='<%=@email%>' type="text" placeholder="Email" style="width:400px;"> &nbsp;                <input type="submit" class="btn" value="確定" style="margin-left:30px;" />
            </div>
        </form>

app/views/acm/search.html.erb
            <div class="input-prepend">
                <span class="add-on"><i class="icon-search"></i></span>
                <input class="span2"  value="" type="text" placeholder="" style="width:400px;" id="searchInput">
                <input type="button" value="Search" class="btn" id="searchBtn"></input>
            </div>
            <div id="searchResult"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wenchang</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar">
    <div class="navbar-inner">
      <a class="brand" href="/">Wenchang</a>
      <ul class="nav">
        <li class="active"><a href="/">Home</a></li>
        <li><%= link_to "fetch",acm_fetch_path%></li>
        <li><%= link_to "search",acm_search_path%></li>
        <li><%=link_to "logout",destroy_user_session_path%></li>
      </ul>
    </div>
  </div>
  <div class="container">
<%= yield %>
</div>
<%= javascript_include_tag "application" %>
</body>
</html>

app/views/papers/_form.html.erb
<%= form_for(@paper) do |f| %>
  <% if @paper.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@paper.errors.count, "error") %> prohibited this paper from being saved:</h2>

      <ul>
      <% @paper.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :source %><br />
    <%= f.text_field :source %>
  </div>
  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :abstract %><br />
    <%= f.text_area :abstract %>
  </div>
  <div class="field">
    <%= f.label :published_at %><br />
    <%= f.datetime_select :published_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/papers/edit.html.erb
<h1>Editing paper</h1>

<%= render 'form' %>

<%= link_to 'Show', @paper %> |
<%= link_to 'Back', papers_path %>

app/views/papers/index.html.erb
<h1>Listing papers</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Source</th>
    <th>Link</th>
    <th>Abstract</th>
    <th>Published at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @papers.each do |paper| %>
  <tr>
    <td><%= paper.name %></td>
    <td><%= paper.source %></td>
    <td><%= paper.link %></td>
    <td><%= paper.abstract %></td>
    <td><%= paper.published_at %></td>
    <td><%= link_to 'Show', paper %></td>
    <td><%= link_to 'Edit', edit_paper_path(paper) %></td>
    <td><%= link_to 'Destroy', paper, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Paper', new_paper_path %>

app/views/papers/new.html.erb
<h1>New paper</h1>

<%= render 'form' %>

<%= link_to 'Back', papers_path %>

app/views/papers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @paper.title %>
</p>

<p>
  <b>Source:</b>
  <%= @paper.source %>
</p>

<p>
  <b>Link:</b>
  <%= @paper.link %>
</p>

<p>
  <b>Abstract:</b>
  <%= @paper.abstract %>
</p>

<p>
  <b>Published at:</b>
  <%= @paper.published_at %>
</p>


<%= link_to 'Edit', edit_paper_path(@paper) %> |
<%= link_to 'Back', papers_path %>

app/views/users/show.html.erb
hi<%=current_user.email%> </br>
<h2>Favorite paper:</h2>
<ul>
<% for item in @user.favorite_paper -%>
  <li><%=link_to(truncate(item.title,:length=>80),"#",{"data-title"=>item.title,"data-content"=>item.abstract,"class"=>"favoritePaper", "rel"=>"tooltip"})%> added at <%=time_ago_in_words(item.created_at)%> ago</li> 
<% end -%>
</ul>